
FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc g++ clang && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY main.cpp .

RUN g++ -O2 -std=c++17 main.cpp -o app-gcc
RUN clang++ -O2 -std=c++17 main.cpp -o app-clang

CMD ["./app-gcc"]